### ISSUE TITLE
License of the operator

### ISSUE THREAD

**Issue by jeyaramashok** [RedisLabs/redis-enterprise-k8s-docs#104]
What's the license of this operator ?

Also is there is plan to open source this operator code ?

I noticed this asked before in https://github.com/RedisLabs/redis-enterprise-k8s-docs/issues/84

**Comment by thalesfsp** [comment]
What's the LICENSE?

**Comment by thalesfsp** [comment]
@yuvallevy2 What's the LICENSE?

**Comment by yuvallevy2** [comment]
The license of the operator is the same as the Redis Enterprise solution license: https://redislabs.com/redis-enterprise-software/pricing/. The operator currently only manages the commercial Redis Enterprise solution. The operator itself (not the Redis Enterprise cluster) might be open-sourced in the near future. In the first phase, it will probably be read-only, but Redis Labs might be willing to accept contributions at a later stage.

**Comment by thalesfsp** [comment]
> The license of the operator is the same as the Redis Enterprise solution license: https://redislabs.com/redis-enterprise-software/pricing/.

It's so confuse... If I understood properly both the operator and Redis Enterprise are **currently NOT open source** - it's proprietary code, also **both CANNOT be used in production** environment WITHOUT a subscription. Is that right @yuvallevy2? Tkx!

**Comment by amiramm** [comment]
@thalesfsp you can use our 30 days trial or if you require a longer trial period or additional information about acquiring a license please contact sales@redislabs.com

Thanks,
Amiram.
