### ISSUE TITLE
ldap integration

### ISSUE THREAD

**Issue by pescarcena** [RedisLabs/redis-enterprise-k8s-docs#128]
Hello, im just want to configure **ldap** using the operator. It's posible?

Just saw Redis documentation: https://docs.redislabs.com/latest/rs/administering/designing-production/security/ldap-integration/?s=ldap

I can't find any information about this.

Cheers.

**Comment by yuvallevy2** [comment]
Hi @pescarcena it should be supported, please approach support@redislabs.com.
Thanks
