### ISSUE TITLE
Have an old cluster that I can't delete

### ISSUE THREAD

**Issue by johnlongo** [RedisLabs/redis-enterprise-k8s-docs#161]
After reinstalling the Operator in a 4.7 ose environment.
The operator thinks there is a cluster already running, but after the reinstall I did not create a new cluster.
Any ideas on how to delete the phantom cluster

<img width="903" alt="2021-03-14_1-58-58" src="https://user-images.githubusercontent.com/23619505/111060293-0cc04f00-8472-11eb-8d21-385f1c02073d.png">

**Comment by laurentdroin** [comment]
Hi,

There is (as you noticed) a REC (Redis Enterprise Cluster) running in your "redis" namespace (project) but from your description, it's not clear how it was created. If you are not able to delete it from the Openshift UI, you should be able to do it from the command line.
On the command line, in the "redis" namespace, run "oc delete rec".

If the operation seems to be hanging and the REC doesn't go away, follow the "REC Deletion" instructions at https://github.com/RedisLabs/redis-enterprise-k8s-docs/blob/master/topics.md#custom-resource-deletion

If this is still not helping, kindly open a Support Ticket with Redis Labs.

**Comment by johnlongo** [comment]
That patch did the trick, thank you
