### ISSUE TITLE
Can't use tolerations

### ISSUE THREAD

**Issue by AlexandreLoman** [RedisLabs/redis-enterprise-k8s-docs#66]
I have seen that it is possible to use toleration with this operator https://github.com/spotahome/redis-operator
Is it possible to use toleration like them with your operator?

**Comment by danni-m** [comment]
@AlexandreLoman we do not support tolerations yet, we do use affinity and node selectors if that helps.

**Comment by amiramm** [comment]
@AlexandreLoman if you provide more information on your use-case we may be able to suggest a way for you to accomplish your goal with the available functionality. You can reach out to me at amiram@redislabs.com

**Comment by danni-m** [comment]
@AlexandreLoman we are tracking this Feature request in our internal ticking system. does this block you from using our operator?

**Comment by amiramm** [comment]
Hi @AlexandreLoman tolerations are supported as of [v6.0.6-6. ](https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.0.6-6)
