### ISSUE TITLE
Database endpoint not accessible after db creation

### ISSUE THREAD

**Issue by yasser583** [RedisLabs/redis-enterprise-k8s-docs#73]
Hello, I'm using Openshift 3.11, after creating a database I'm unable to reach its endpoint:
**redis-18000.redis-enterprise.redis-enterprise.svc.cluster.local:18000 / 10.128.6.20:18000**
```
# ping redis-18000.redis-enterprise.redis-enterprise.svc.cluster.local
ping: redis-18000.redis-enterprise.redis-enterprise.svc.cluster.local: Name or service not known
# oc rsh redis-enterprise-0
redis-cli -h redis-18000.redis-enterprise.redis-enterprise.svc.cluster.local -p 18000
Could not connect to Redis at redis-18000.redis-enterprise.redis-enterprise.svc.cluster.local:18000: Name or service not known
```
It works fine if I use the IP:
```
# redis-cli -h 10.128.6.20 -p 18000
10.128.6.20:18000>
```
Please your help.

**Comment by danni-m** [comment]
Hi @yasser583, unlike other installations of Redis Enterprise in k8s we use a different DNS method that is not propagate in the ui.
Your db endpoint will be *DB_NAME*.redis-enterprise.svc.cluster.local (DB_NAME.NAMESPACE.svc.cluster.local).
You can also see these services by running `kubectl get services`.

**Comment by danni-m** [comment]
Closing this as a known limitation.
