### ISSUE TITLE
Is there a way to specify the Services Rigger(k8s-controller) image?

### ISSUE THREAD

**Issue by marpio** [RedisLabs/redis-enterprise-k8s-docs#78]
There are two reasons for that:
1. I'm on a air-gaped (mostly) cluster and hub.docker.io is not available.
2. registry.connect.redhat.com is available and so redis entrerprise and operator images are being pulled from there. Still the Services Rigger Deployment is trying to pull the image from docker.io.

One solution would be to extend `RedisEnterpriseCluster` and add something like `servicesRiggerImageSpec` (similar to `redisEnterpriseImageSpec`). 
Another option would be to use the image from registry.connect.redhat.com in case the operator and redis-enterprise images from that registry are used.

**Comment by ushachar** [comment]
It's already possible -- just add a redisEnterpriseServicesRiggerImageSpec section in the redis-enterprise-cluster_rhel.yaml 

@danni-m / @amiramm  - need to add this to the documentation.

**Comment by amiramm** [comment]
Hi @marpio ,

When using non-dockerhub repos or in an airgapped environment, please explicitly specify the Services Rigger image by using the following definition under the redis-enterprise-cluster.yaml / redis-enterpries-cluster_rehl.yaml spec section:
redisEnterpriseServicesRiggerImageSpec:
 imagePullPolicy: IfNotPresent
 repository: [your repository path]
 versionTag: [version tag]

**Comment by marpio** [comment]
Thank you @ushachar and @amiramm
