### ISSUE TITLE
collect_resources_list should be using namespace

### ISSUE THREAD

**Issue by slgan** [RedisLabs/redis-enterprise-k8s-docs#93]
collect_resources_list is not using kubectl get all -n <namespace>
Without using namespace, it is getting the listing from default namespace which has nothing to do with the Redis Enterprise deployment inside a namespace.

Should be:
def collect_resources_list(namespace, output_dir):
    """
        Prints the output of kubectl get all to a file
    """
    cmd = "kubectl get all -n {}".format(namespace)
    collect_helper(output_dir, cmd=cmd, file_name="resources_list", resource_name="resources list")

Corresponding change for line 57:
from
    collect_resources_list(output_dir)
to
    collect_resources_list(namespace, output_dir)

**Comment by laurentdroin** [comment]
Thanks Gan. I will soon submit the pull request for this.

**Comment by amiramm** [comment]
Fixed in https://github.com/RedisLabs/redis-enterprise-operator/pull/310 by @laurentdroin 
Closing.
