### ISSUE TITLE
No proveisioner for backend PVs

### ISSUE THREAD

**Issue by mrafieee** [RedisLabs/redis-enterprise-k8s-docs#95]
I am running this operator in an air gaped env, which we do not have any PV provisioners I have a the PVs created manually but not able to assign them to respective redis pods as PVC .

is there any options to pass PV names to operator?

```

Failed Scheduling | pod has unbound PersistentVolumeClaims (repeated 4 times)

```

**Comment by mrafieee** [comment]
What I did around this was I created the PV and PVC in the redis operator expected way and when redis came online it just picked it up.

**Comment by danni-m** [comment]
@mrafieee thats a nice workaround, its hard to support this kind of thing, since the PV/PVC are controlled by the STS. I would do the same thing as you.
