### ISSUE TITLE
README.md --different output

### ISSUE THREAD

**Issue by JoshuaFox** [RedisLabs/redis-enterprise-k8s-docs#98]
README.md has
> You should receive the following response:

     `clusterrolebinding.rbac.authorization.k8s.io/redis-enterprise-operator configured`

I actually received 
```
role.rbac.authorization.k8s.io/redis-enterprise-operator created
serviceaccount/redis-enterprise-operator created
rolebinding.rbac.authorization.k8s.io/redis-enterprise-operator created
```

**Comment by danni-m** [comment]
@JoshuaFox thanks! we'll update it.
